name: sobar_app
description: "An app to search London's pubs for no and low alcohol drinks."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-190.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  hexcolor: ^3.0.1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/backgrounds/
  - assets/logos/
  - assets/icons/
  - assets/lucky_saint_pubs_london.json

  fonts:
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: Work Sans
      fonts:
        - asset: assets/fonts/WorkSans-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/WorkSans-VariableFont_wght.ttf
